src/UrgentCast/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using UrgentCast.Data;

namespace UrgentCast.Controllers
{
    public class HomeController : Controller
    {
        private readonly ApplicationDbContext _context;

        public HomeController (ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var feeds = _context.Feeds
                .Include(p => p.Episodes)
                .OrderBy(p => p.Title)
                .ToList();
            
            feeds.ForEach(f => 
            {
                // Order the episodes in descending order of publication date
                f.Episodes = f.Episodes
                    .OrderByDescending(e => e.PublishedAt)
                    .Take(20)
                    .ToList();
            });

            return View(feeds);
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

src/UrgentCast/ViewComponents/LatestEpisodeViewComponent.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using UrgentCast.Data;
using UrgentCast.Models;

namespace UrgentCast.ViewComponents
{
    public class LatestEpisodeViewComponent : ViewComponent
    {
        private readonly ApplicationDbContext _context;

        public LatestEpisodeViewComponent (ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<IViewComponentResult> InvokeAsync(int maxPriority, bool isDone)
        {
            var episode = _context.Episodes
                .OrderByDescending(e => e.PublishedAt)
                .FirstOrDefault();

            return View<Episode>(episode);
        }
    }
}

src/UrgentCast/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}

<div class="ui container">
    <h2>@ViewData["Title"].</h2>
    <h3>@ViewData["Message"]</h3>

    <p>Use this area to provide additional information.</p> 
</div>

src/UrgentCast/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<div class="ui container">
    <h2>@ViewData["Title"]</h2>
    <h3>@ViewData["Message"]</h3>
    <address>
        One Microsoft Way<br/>
        Redmond, WA 98052-6399<br/>
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>
</div>

src/UrgentCast/Views/Home/Index.cshtml
@model IEnumerable<UrgentCast.Models.Feed>
@{
    ViewData["Title"] = "Home Page";
}

@await Component.InvokeAsync("LatestEpisode")

@foreach (var feed in Model)
{
    <h2 class="ui header">
        <i class="sound icon"></i>
        <div class="content">@feed.Title</div>
    </h2>

    <div class="ui three stackable cards">
        @foreach (var episode in feed.Episodes)
        {
            <div class="card">
                <div class="content">
                    <div class="header">
                        @episode.ShowNumber - @episode.Title
                    </div>
                    <div class="meta">
                        @episode.PublishedAt
                    </div>
                    <div class="ui divider"></div>
                    <div class="meta">
                        @episode.Subtitle
                    </div>
                    <div class="description">
                        @episode.Description
                    </div>
                </div>
                <div class="extra content">
                    <audio controls="controls">
                        <source src="@episode.MediaUrl" type="audio/mpeg">
                        Your browser does not support audio. You can still download the show though!
                    </audio>
                </div>
            </div>
        }
    </div>
}